### ISSUE TITLE
Handlers not properly registering with Next.js when using faker v6 or 7

### ISSUE THREAD

**Issue by dustinsgoodman** [mswjs/data#226] opened 2022-06-23 23:22 UTC
# Issue
When using [faker-js](https://github.com/faker-js/faker) v6 or v7 with msw and mswjs/data, the server fails to initiate the worker. It appears as though the the handlers are getting corrupted somehow. I've been able to recreate the issue in this Stackblitz for your review: https://stackblitz.com/edit/nextjs-bfqzrz?file=package.json

This is what you should see on load:
<img width="754" alt="image" src="https://user-images.githubusercontent.com/1815379/175430349-92b58888-28d8-4930-9cca-d5a771193709.png">

I went with the bare minimum reproduction and used mostly example code from https://github.com/vercel/next.js/tree/canary/examples/with-msw as the base. 

Libraries used:
- nextjs v12.1
- @faker-js/faker 7.3.0 and 6.3.1 (I tried both!)
- @mswjs/data 0.10.1
- msw 0.42.3

**Comment by kettanaito** [comment] 2022-06-24 09:59
Hey, @dustinsgoodman. Thanks for reporting this.

This issue is a duplicate of:

- https://github.com/mswjs/msw/discussions/1236

If you follow the answer to that discussion you will get this issue resolved.

**Closed by kettanaito** 2022-06-24 09:59 UTC

**Comment by dustinsgoodman** [comment] 2022-06-24 15:23
Hey @kettanaito - I don't think this is a duplicate and is rather an issue with integration with faker itself. When I comment out faker in https://stackblitz.com/edit/nextjs-bfqzrz?file=mocks/db.js, the server error changes and the handlers are actually able to register. Stackblitz has issues with the worker registration but you can see the error completely changes from the one describes in https://github.com/mswjs/msw/discussions/1236

**Comment by kettanaito** [comment] 2022-06-24 23:17
Have you tried following the proposed answer in that discussion while using Faker?

I don't argue that Faker may affect things, like being shipped in an ESM or something, which automagically flips how webpack resolves modules under the hood, but the error message on the screenshot above is very likely about the conditional imports.

**Comment by dustinsgoodman** [comment] 2022-06-27 04:45
I hadn't quite followed you and you meant to go to https://github.com/mswjs/msw/issues/1227#issuecomment-1118492523 🤦 - that worked perfectly. I'll go open up a quick PR to update https://github.com/vercel/next.js/blob/canary/examples/with-msw/mocks/index.js because that would save people lots of headaches.

**Comment by dustinsgoodman** [comment] 2022-07-06 19:43
@kettanaito got it fixed upstream in next.js 😄 https://github.com/vercel/next.js/pull/38050
