### ISSUE TITLE
Problem with manyOf relation

### ISSUE THREAD

**Issue by tafuri-m** [mswjs/data#108] opened 2021-07-26 12:44 UTC
I had problem with the relation manyOf, in my example i had a user that can create many courses.
The GraphQL type of field "courses" in "user" model is declared String, instead of the model type of "course" so I will receive the following error:

Query1:
```
query Users {
  users {
	  username
	  email
	  courses 
  }
}
```
Error1:
`{"errors":[{"message":"String cannot represent value: [{ id: \"c407a7bd-7930-43bc-8241-2aafd058ed39\", title: \"Quisquam debitis nostrum.\", subtitle: \"Sint ut quo magni perspiciatis esse qui omnis.\", type: \"course\" }]","locations":[{"line":6,"column":8}],"path":["users",0,"courses"]}],"data":{"users":[{"username":"Rozella","email":"Idella54@gmail.com","courses":null}]}}` 

Query2:
```
query Users {
  users {
	  username
	  email
	  courses {
		  title
	  }
  }
}
```

`{"errors":[{"message":"Field \"courses\" must not have a selection since type \"String\" has no subfields.","locations":[{"line":6,"column":16}]}]}`

Definition of relations:
```
export const db = factory({
	user: {
		id: primaryKey(String),
		username: String,
		email: String,
		courses: manyOf("course")
	},
	course: {
		id: primaryKey(String),
		title: String,
		subtitle: String,
		type: String
	}
})
```

**Comment by kettanaito** [comment] 2021-07-26 13:46
Hey, @tafuri-m. Thanks for raising this. 

I believe this is a duplicate of #99. Please follow the updates about this issue in the said ticket. Thanks.

**Closed by kettanaito** 2021-07-26 13:46 UTC
